### ISSUE TITLE
Kartet fungerer ikke.

### ISSUE THREAD

**Issue by flexd** [atombender/bysykkel#1]
Ser at siste commit er 4 år gammel. Jeg fant dette prosjektet i dag, og kartet laster ikke pga. en feilmelding, men dataene ser ut til å være der. (stations.json har data).

Noe som har forandret seg eller er det noe annet galt? Vet ikke om folk bruker dette engang jeg.

**Comment by atombender** [comment]
Heh, det er også fire år siden jeg brukte dette. Det er nok fordi den bruker en gammel versjon av Google Maps-APIet. Det kan også være at APIet har endret seg. Jeg kan sjekke litt.

**Comment by flexd** [comment]
Er jo ikke så fryktelig viktig, bare syntes det hadde vært nyttig :-)
